name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
  
      - name: Pylint
        run: pylint --fail-under=9 voxelgym2D

      - name: Mypy
        run: mypy voxelgym2D

      - name: Isort
        run: isort --check-only --diff voxelgym2D tests examples

      - name: Black
        run: black --check --diff voxelgym2D tests examples -l 120

      - name: Pytest
        run: |
          coverage run --source voxelgym2D -m pytest tests/
          coverage report -m


